# Generated by Django 2.2 on 2020-04-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
