# Generated by Django 2.2 on 2020-04-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200408_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivered',
            new_name='received',
        ),
    ]
