# Generated by Django 2.2 on 2020-04-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200408_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
